# Generated by Django 5.1.1 on 2024-10-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_choice', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'ordering': ['agency_choice'],
            },
        ),
        migrations.CreateModel(
            name='attentionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_choice', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Attention',
                'verbose_name_plural': 'Attentions',
                'ordering': ['attention_choice'],
            },
        ),
        migrations.CreateModel(
            name='documentTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_choice', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['document_choice'],
            },
        ),
        migrations.CreateModel(
            name='outModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_choice', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Output',
                'verbose_name_plural': 'Outputs',
                'ordering': ['out_choice'],
            },
        ),
        migrations.CreateModel(
            name='sourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_choice', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['source_choice'],
            },
        ),
        migrations.CreateModel(
            name='statusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'ordering': ['status_choice'],
            },
        ),
        migrations.CreateModel(
            name='subjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_choice', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['subject_choice'],
            },
        ),
        migrations.CreateModel(
            name='toModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_choice', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
                'ordering': ['to_choice'],
            },
        ),
        migrations.CreateModel(
            name='unitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_choice', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['unit_choice'],
            },
        ),
        migrations.CreateModel(
            name='workgroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workgroup_choice', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Workgroup',
                'verbose_name_plural': 'Workgroups',
                'ordering': ['workgroup_choice'],
            },
        ),
    ]
